import Phaser from 'phaser';
import { BaseBiomeScene } from './BaseBiomeScene';
import { FOREST_SCREENS } from '../../../shared/world/forest';

/**
 * The Forest hub (`forest_anchorage`) composes several tilesets and a second
 * `above-ground` layer (structures + foliage over the terrain). Each entry is
 * [map-tileset-name, image path]; the texture key MUST equal the tileset's name in
 * the map so buildTilesets() can resolve gids by name. `charsetA_1` (the map's npcs
 * layer) is intentionally omitted — merchant NPCs are spawned as interactive charset
 * sprites from the objects layer, so the static npcs layer is not rendered.
 */
const FOREST_HUB_TILESETS: ReadonlyArray<readonly [string, string]> = [
  ['forest16', 'assets/tiles/forest16.png'],
  ['Fantasy Era- Wild plains pack', 'assets/tiles/regions/woods/Fantasy Era- Wild plains pack.png'],
  ['ModernEra_GreenForest_Tileset', 'assets/tiles/regions/woods/ModernEra_GreenForest_Tileset.png'],
  ['asset_alliance_starter_village_main', 'assets/tiles/regions/woods/asset_alliance_starter_village_main.png'],
  ['berry_and_trees', 'assets/tiles/regions/woods/berry_and_trees.png'],
];

/**
 * The Forest region (GDD §10.15/§10.17, Phase 8E.1). A BaseBiomeScene subclass that
 * drives the multi-screen Forest manifest (FOREST_SCREENS): walking into a screen
 * edge with a defined exit fade-transitions to the neighbouring screen, spawning the
 * player at the opposite edge.
 *
 * All 15 screens — including the hub `forest_anchorage` — use the deterministic
 * per-screen maps generated by gen-forest-screens.mjs (the legacy overworld.json
 * exception was removed in #107). The hub's generated map carries open perimeter gaps
 * at its four exits, so the manifest exits are walkable like every other screen.
 */
export class ForestScene extends BaseBiomeScene {
  constructor() {
    super({ key: 'ForestScene' });
  }

  init(data?: { screenId?: string; spawnEdge?: string }): void {
    this.screenId = data?.screenId ?? 'forest_anchorage';
    this.screenDef = FOREST_SCREENS.find((s) => s.id === this.screenId);
    window.__forestScreenId = this.screenId;
  }

  tilesetKey(): string {
    // forest_anchorage is the hand-authored 16px Forest hub (multi-tileset; see
    // buildTilesets). 'forest16' is its primary/ground tileset. Every other screen
    // stays on the 32px `forest` tileset at 1× until the full 16px migration.
    return this.screenId === 'forest_anchorage' ? 'forest16' : 'forest';
  }

  mapKeyForScreen(id: string): string {
    return 'forest_' + id;
  }

  /**
   * The Forest hub registers all of its tilesets (each preloaded under a key equal
   * to its name in the map); every other screen uses the single-tileset default.
   * Tilesets whose texture is absent (e.g. the npcs `charsetA_1` sheet, not loaded
   * as a tile image) are skipped — no rendered layer references them.
   */
  protected buildTilesets(map: Phaser.Tilemaps.Tilemap): Phaser.Tilemaps.Tileset[] {
    if (this.screenId !== 'forest_anchorage') return super.buildTilesets(map);
    return map.tilesets
      .filter((t) => this.textures.exists(t.name))
      .map((t) => map.addTilesetImage(t.name, t.name))
      .filter((t): t is Phaser.Tilemaps.Tileset => t !== null);
  }

  /**
   * The Forest hub uses three tile layers:
   *   ground    — terrain base (grass, water, paths)
   *   behind    — building south walls + tree trunks: renders below the player
   *   in-front  — roofs + tree canopy: renders above the player
   */
  protected tileLayerNames(): string[] {
    return this.screenId === 'forest_anchorage'
      ? ['ground', 'behind', 'in-front']
      : super.tileLayerNames();
  }

  /**
   * `behind` uses 'non-empty' so walls and trunks physically block movement.
   * `in-front` uses the default 'property' mode — none of the roof/canopy tiles
   *  carry a `collides` property, so they produce zero collision (player walks under).
   */
  protected tileLayerCollisionMode(layerName: string): 'property' | 'non-empty' {
    if (this.screenId === 'forest_anchorage' && layerName === 'behind') return 'non-empty';
    return super.tileLayerCollisionMode(layerName);
  }

  /**
   * Depth order:
   *   ground   = 0  (terrain)
   *   player   = 3  (set in BaseBiomeScene.create)
   *   behind   = 2  (south walls render just below the player)
   *   in-front = 5  (roofs + canopy render above the player; NPCs at 6)
   */
  protected tileLayerDepth(layerName: string): number {
    if (this.screenId !== 'forest_anchorage') return super.tileLayerDepth(layerName);
    if (layerName === 'behind') return 2;
    if (layerName === 'in-front') return 5;
    return 0; // ground
  }

  /**
   * The hub map (`forest_anchorage`) includes the Sanctum building as hand-authored
   * Tiled tiles (ground / behind / in-front layers), so the generated
   * `sanctum-exterior.png` sprite would double-render over the same spot and appear
   * twice the expected size at 2× zoom. Return false to skip the sprite; the
   * sanctum_return interaction zone is still built normally.
   */
  protected shouldDrawSanctumExterior(): boolean {
    return this.screenId !== 'forest_anchorage';
  }

  preload(): void {
    if (this.screenId === 'forest_anchorage') {
      // The hub composes several tilesets; load each under a key equal to its map name.
      for (const [key, path] of FOREST_HUB_TILESETS) {
        if (!this.textures.exists(key)) this.load.image(key, path);
      }
    } else if (!this.textures.exists('forest')) {
      this.load.image('forest', 'assets/tiles/forest.png');
    }
    this.loadCommonAssets();
    // Every screen — including the hub — loads its deterministic generated map (#107).
    this.load.tilemapTiledJSON(
      this.mapKeyForScreen(this.screenId),
      `assets/maps/forest/${this.screenId}.json`,
    );
  }

  /**
   * The hub's west column (col 0) has gid 3 collision only at rows 0-1, 13, and
   * 23-26. Rows 2-12 and 18-22 and 27-28 use walkable tiles — the perimeter is
   * visually a wall but physically open. Add invisible static physics zones to
   * close those gaps, leaving rows 14-17 (y 224-287) open for the west road exit.
   *
   * The zones are 28 px wide (x 0-27) so a blocked player stops at x ≈ 26, which
   * is above the EDGE=24 px exit threshold and therefore does NOT trigger the
   * west screen transition. Only the road gap (no zone) lets the player get close
   * enough to trigger the exit.
   */
  onEnterScreen(): void {
    if (this.screenId !== 'forest_anchorage') return;
    const W = 28; // wider than EDGE=24 so blocked players don't trip the exit
    const addWall = (yTop: number, yBottom: number): void => {
      const h = yBottom - yTop;
      const zone = this.add.zone(W / 2, yTop + h / 2, W, h);
      this.physics.add.existing(zone, true);
      this.physics.add.collider(this.getPlayer(), zone);
    };
    // Above the west road opening: rows 2-12 = y 32-207
    addWall(32, 208);
    // Below the west road opening: rows 18-22 = y 288-367 (rows 23-26 already gid 3)
    addWall(288, 368);
    // Bottom gap: rows 27-28 = y 432-463
    addWall(432, 464);
  }

  /**
   * #137 — apply the 2× world zoom on the 16px proof screen (forest_anchorage)
   * after the base scene has built the world + dual-camera split. cameras.main is
   * the world camera (zoomed); uiCam (set up in BaseBiomeScene.create) stays at 1:1
   * so the HUD/overlays are unaffected. Other screens keep the default 1× zoom.
   */
  create(): void {
    super.create();
    if (this.screenId === 'forest_anchorage') {
      this.cameras.main.setZoom(2);
    }
  }
}
