import Phaser from 'phaser';
import { BaseBiomeScene } from './BaseBiomeScene';
import { FOREST_SCREENS } from '../../../shared/world/forest';
import { ElementEnum } from '../../../shared/types';
import { ShrineZone } from '../objects/world/ShrineZone';

/**
 * The Forest hub (`forest_anchorage`) composes several tilesets and a second
 * `above-ground` layer (structures + foliage over the terrain). Each entry is
 * [map-tileset-name, image path]; the texture key MUST equal the tileset's name in
 * the map so buildTilesets() can resolve gids by name. `charsetA_1` (the map's npcs
 * layer) is intentionally omitted — merchant NPCs are spawned as interactive charset
 * sprites from the objects layer, so the static npcs layer is not rendered.
 */
const FOREST_HUB_TILESETS: ReadonlyArray<readonly [string, string]> = [
  ['forest16', 'assets/terrain/terrain_forest_void.png'],
  ['terrain_forest_void', 'assets/terrain/terrain_forest_void.png'],
  ['Fantasy Era- Wild plains pack', 'assets/terrain/terrain_plains_fantasy.png'],
  ['ModernEra_GreenForest_Tileset', 'assets/terrain/terrain_forest_modern.png'],
  ['asset_alliance_starter_village_main', 'assets/structures/tileset_village_main_a.png'],
  ['berry_and_trees', 'assets/flora/flora_berries_trees.png'],
];

// Tilesets loaded for generated (non-hub) 16px Forest screens (EPIC #149 / #157).
// Keys MUST match the `name` fields in GENERATED_TILESETS (forest-gid-map.mjs) so
// the firstgid contract baked into each generated map JSON resolves correctly.
export const FOREST_GENERATED_TILESETS: ReadonlyArray<readonly [string, string]> = [
  ['autotile_water_16', 'assets/terrain/autotile_water_16.png'],
  ['ModernEra_GreenForest_Tileset', 'assets/terrain/terrain_forest_modern.png'],
  ['berry_and_trees', 'assets/flora/flora_berries_trees.png'],
  ['terrain_plains_fantasy', 'assets/terrain/terrain_plains_fantasy.png'],
  ['tileset_village_main_a', 'assets/structures/tileset_village_main_a.png'],
  ['terrain_forest_void', 'assets/terrain/terrain_forest_void.png'],
  // Legacy tilesets — referenced by screens generated before PR #250 (boss_clearing,
  // briar_pass, glade, hollow, hidden_alcove, swamp_gate). buildTilesets() filters
  // by this.textures.exists so these are no-ops for new-format maps.
  ['autotile_grass_16', 'assets/terrain/autotile_grass_16.png'],
  ['autotile_dirt_16', 'assets/terrain/autotile_dirt_16.png'],
  ['autotile_cliff_16', 'assets/terrain/autotile_cliff_16.png'],
];

// Tilesets for hand-authored Forest screens (forest_deepwood, forest_mossy_fen,
// forest_south_path, forest_boss_clearing, …). Extends the generated base with
// every extra tileset used across those maps; buildTilesets() filters to only
// what each map declares.
// The three legacy autotile tilesets are included so screens that were generated
// before PR #250 (crossroads, briar_pass, glade, hollow, hidden_alcove, ridge)
// still resolve their GIDs correctly. buildTilesets() only registers tilesets
// the map's JSON actually declares, so these are no-ops for new-format maps.
const FOREST_HANDAUTHORED_TILESETS: ReadonlyArray<readonly [string, string]> = [
  ...FOREST_GENERATED_TILESETS,
  ['autotile_grass_16', 'assets/terrain/autotile_grass_16.png'],
  ['autotile_dirt_16', 'assets/terrain/autotile_dirt_16.png'],
  ['autotile_cliff_16', 'assets/terrain/autotile_cliff_16.png'],
  ['terrain_mossy_swamp_16', 'assets/terrain/terrain_mossy_swamp_16.png'],
  ['terrain_forest_modern', 'assets/terrain/terrain_forest_modern.png'],
  ['terrain_forest_deepwoods', 'assets/terrain/terrain_forest_deepwoods.png'],
  ['tileset_village_main_b', 'assets/structures/tileset_village_main_b.png'],
  // Snow tilesets — forest_snow_gate (the biome-transition screen) mixes forest
  // terrain with the snow palette. Keys match the tileset names declared in the
  // map JSON (autoTile_snow / ts_snow) so buildTilesets() can resolve them.
  ['autoTile_snow', 'assets/terrain/autotile_snow_16.png'],
  ['ts_snow', 'assets/terrain/terrain_snow_main.png'],
];

/**
 * The Forest region (GDD §10.15/§10.17, Phase 8E.1). A BaseBiomeScene subclass that
 * drives the multi-screen Forest manifest (FOREST_SCREENS): walking into a screen
 * edge with a defined exit fade-transitions to the neighbouring screen, spawning the
 * player at the opposite edge.
 *
 * All 15 screens — including the hub `forest_anchorage` — use the deterministic
 * per-screen maps generated by gen-forest-screens.mjs (the legacy overworld.json
 * exception was removed in #107). The hub's generated map carries open perimeter gaps
 * at its four exits, so the manifest exits are walkable like every other screen.
 */
export class ForestScene extends BaseBiomeScene {
  /** #231 — the Thornado Fusion Shrine altar on forest_thornado_shrine, or null. */
  private shrineZone: ShrineZone | null = null;

  constructor() {
    super({ key: 'ForestScene' });
  }

  init(data?: { screenId?: string; spawnEdge?: string }): void {
    // Tear down the previous screen's shrine before the new screen reuses the
    // scene instance — prevents stale overlays/listeners on screen transitions.
    this.shrineZone?.destroy();
    this.shrineZone = null;
    this.screenId = data?.screenId ?? 'forest_anchorage';
    this.screenDef = FOREST_SCREENS.find((s) => s.id === this.screenId);
    window.__forestScreenId = this.screenId;
  }

  /**
   * Whether this screen uses 16px tiles + 2× world zoom (the rich rendering path).
   * Currently only `forest_anchorage` (the hand-authored hub) qualifies; the full
   * 16px migration of generated screens is a later issue. Structuring the decision
   * as a single predicate means every rendering branch (tilesets, layers, zoom,
   * Sanctum) reads this method rather than repeating the id literal.
   */
  protected is16pxScreen(): boolean {
    // All Forest screens use 16px tiles + 2× zoom after #149/#159. The hub
    // (forest_anchorage) is hand-authored with the hub tilesets; every generated
    // screen uses FOREST_GENERATED_TILESETS (forked in preload()).
    return true;
  }

  tilesetKey(): string {
    // is16pxScreen() screens use the 16px hub tilesets (primary: 'forest16');
    // every other screen stays on the 32px `forest` tileset at 1× until the
    // full 16px migration.
    return this.is16pxScreen() ? 'forest16' : 'forest';
  }

  mapKeyForScreen(id: string): string {
    return 'forest_' + id;
  }

  /**
   * The Forest hub registers all of its tilesets (each preloaded under a key equal
   * to its name in the map); every other screen uses the single-tileset default.
   * Tilesets whose texture is absent (e.g. the npcs `charsetA_1` sheet, not loaded
   * as a tile image) are skipped — no rendered layer references them.
   */
  protected buildTilesets(map: Phaser.Tilemaps.Tilemap): Phaser.Tilemaps.Tileset[] {
    if (!this.is16pxScreen()) return super.buildTilesets(map);
    return map.tilesets
      .filter((t) => this.textures.exists(t.name))
      .map((t) => map.addTilesetImage(t.name, t.name))
      .filter((t): t is Phaser.Tilemaps.Tileset => t !== null);
  }

  /**
   * 16px screens use three tile layers (GDD §10 3-layer contract, #149):
   *   ground    — terrain base (grass, water, paths)       depth 0
   *   behind    — building south walls + tree trunks        depth 2 (below player)
   *   in-front  — roofs + tree canopy                      depth 5 (above player)
   * Every other Forest screen stays on the single 'ground' layer.
   */
  protected tileLayerNames(): string[] {
    return this.is16pxScreen()
      ? ['ground', 'behind', 'in-front']
      : super.tileLayerNames();
  }

  /**
   * `behind` uses 'non-empty' so walls and trunks physically block movement.
   * `in-front` uses the default 'property' mode — none of the roof/canopy tiles
   *  carry a `collides` property, so they produce zero collision (player walks under).
   *
   * Exception: forest_snow_gate has ts_snow bridge tiles in `behind` that must be
   * walkable. Those tiles carry no `collides` property; the obstacle tiles in that
   * map (berry_and_trees, terrain_plains_fantasy) are tagged `collides: true` in
   * the map JSON, so 'property' mode handles both correctly.
   */
  protected tileLayerCollisionMode(layerName: string): 'property' | 'non-empty' {
    if (this.is16pxScreen() && layerName === 'behind' && this.screenId !== 'forest_snow_gate')
      return 'non-empty';
    return super.tileLayerCollisionMode(layerName);
  }

  /**
   * Depth order (GDD #149 contracts):
   *   ground   = 0  (terrain)
   *   player   = 3  (set in BaseBiomeScene.create)
   *   behind   = 2  (south walls render just below the player)
   *   in-front = 5  (roofs + canopy render above the player; NPCs at 6)
   */
  protected tileLayerDepth(layerName: string): number {
    if (!this.is16pxScreen()) return super.tileLayerDepth(layerName);
    if (layerName === 'behind') return 2;
    if (layerName === 'in-front') return 5;
    return 0; // ground
  }



  preload(): void {
    if (this.screenId === 'forest_anchorage') {
      // Hub: hand-authored multi-tileset map; load each under a key equal to its map name.
      for (const [key, path] of FOREST_HUB_TILESETS) {
        if (!this.textures.exists(key)) this.load.image(key, path);
      }
    } else if (['forest_deepwood', 'forest_mossy_fen', 'forest_south_path', 'forest_snow_gate', 'forest_north_road', 'forest_east_path', 'forest_crossroads', 'forest_ridge', 'forest_boss_clearing'].includes(this.screenId)) {
      // Hand-authored maps; load the full extra tileset pool — buildTilesets() filters
      // to only what each map's JSON actually declares.
      for (const [key, path] of FOREST_HANDAUTHORED_TILESETS) {
        if (!this.textures.exists(key)) this.load.image(key, path);
      }
    } else {
      // Generated screens: the 6-tileset GID contract from #157/#159.
      for (const [key, path] of FOREST_GENERATED_TILESETS) {
        if (!this.textures.exists(key)) this.load.image(key, path);
      }
    }
    this.loadCommonAssets();
    // Every screen — including the hub — loads its deterministic generated map (#107).
    this.load.tilemapTiledJSON(
      this.mapKeyForScreen(this.screenId),
      `assets/maps/forest/${this.screenId}.json`,
    );
  }

  /**
   * The hub's west column (col 0) has gid 3 collision only at rows 0-1, 13, and
   * 23-26. Rows 2-12 and 18-22 and 27-28 use walkable tiles — the perimeter is
   * visually a wall but physically open. Add invisible static physics zones to
   * close those gaps, leaving rows 14-17 (y 224-287) open for the west road exit.
   *
   * The zones are 28 px wide (x 0-27) so a blocked player stops at x ≈ 26, which
   * is above the EDGE=24 px exit threshold and therefore does NOT trigger the
   * west screen transition. Only the road gap (no zone) lets the player get close
   * enough to trigger the exit.
   */
  onEnterScreen(): void {
    // #231 — the Thornado Fusion Shrine screen places a sealed altar the player
    // unseals with a Thornado ring-key won from the Shrine Guardian sub-boss.
    if (this.screenId === 'forest_thornado_shrine') {
      this.buildThornadoShrine();
      return;
    }
    // #232 — the Bloom Fusion Shrine screen places an always-open altar (no seal):
    // it is craftable from the first visit, independent of the Bloom Guardian.
    if (this.screenId === 'forest_bloom_hollow') {
      this.buildBloomShrine();
      return;
    }
    // Hub-only: the hand-authored hub perimeter needs invisible wall zones to close
    // its visually-walled-but-physically-open gaps. Generated screens have a real
    // T_CLIFF perimeter with carved exit gaps and need none.
    if (this.screenId !== 'forest_anchorage') return;
    const W = 28; // wider than EDGE=24 so blocked players don't trip the exit
    const addWall = (yTop: number, yBottom: number): void => {
      const h = yBottom - yTop;
      const zone = this.add.zone(W / 2, yTop + h / 2, W, h);
      this.physics.add.existing(zone, true);
      this.physics.add.collider(this.getPlayer(), zone);
    };
    // Above the west road opening: rows 2-12 = y 32-207
    addWall(32, 208);
    // Below the west road opening: rows 18-22 = y 288-367 (rows 23-26 already gid 3)
    addWall(288, 368);
    // Bottom gap: rows 27-28 = y 432-463
    addWall(432, 464);
  }

  /**
   * #231 — Build the Thornado Fusion Shrine on forest_thornado_shrine. The
   * generated map carries no dedicated altar object (only a `spawn`), so we
   * synthesize a 32×32px altar zone near the top-centre of the 40×30-tile clearing
   * (tile ~(20, 8) → world (328, 136)), clear of the player spawn (x≈24) and the
   * Shrine Guardian patrol (tile (20, 15)). The {@link ShrineZone} owns the
   * altar's sealed/open state and the ring-key unseal flow; its `onShrineOpen`
   * opens the Fusion modal pre-filtered to Thornado (Wood+Wind).
   */
  private buildThornadoShrine(): void {
    const ALTAR_PX = 32;
    const altarObj: Phaser.Types.Tilemaps.TiledObject = {
      id: -231,
      name: 'shrine',
      type: 'shrine',
      // Tile (20, 8) center at 16px = (328, 136); top-left for a 32px altar.
      x: 328 - ALTAR_PX / 2,
      y: 136 - ALTAR_PX / 2,
      width: ALTAR_PX,
      height: ALTAR_PX,
    };
    this.shrineZone = new ShrineZone(
      this,
      altarObj,
      'forest_thornado_shrine',
      ElementEnum.THORNADO,
      () => void this.openShrineFusion(ElementEnum.THORNADO),
    );
    this.registerInteractionZone(
      this.shrineZone.interactionZone,
      this.shrineZone.altarObjects,
    );
  }

  /**
   * #232 — Build the Bloom Fusion Shrine on forest_bloom_hollow. Like the Thornado
   * screen the generated map carries no altar object (only a `spawn`), so we
   * synthesize a 32×32px altar zone in the upper-centre of the 38×30-tile hollow
   * (tile (19, 8) → world (312, 136)), clear of the player spawn (world ≈(584, 248))
   * and the Bloom Guardian patrol (tile (20, 15)). The Bloom altar is ALWAYS open
   * (`alwaysOpen: true`): no seal, no ring-key, no confirmation — pressing E opens
   * the Fusion modal pre-filtered to Bloom (Wood+Earth) from the first visit.
   */
  private buildBloomShrine(): void {
    const ALTAR_PX = 32;
    const altarObj: Phaser.Types.Tilemaps.TiledObject = {
      id: -232,
      name: 'shrine',
      type: 'shrine',
      // Tile (19, 8) center at 16px = (312, 136); top-left for a 32px altar.
      x: 312 - ALTAR_PX / 2,
      y: 136 - ALTAR_PX / 2,
      width: ALTAR_PX,
      height: ALTAR_PX,
    };
    this.shrineZone = new ShrineZone(
      this,
      altarObj,
      'forest_bloom_hollow',
      ElementEnum.BLOOM,
      () => void this.openShrineFusion(ElementEnum.BLOOM),
      true, // alwaysOpen — the Bloom altar has no seal
    );
    this.registerInteractionZone(
      this.shrineZone.interactionZone,
      this.shrineZone.altarObjects,
    );
  }
}
