import { BaseBiomeScene } from './BaseBiomeScene';
import { FOREST_SCREENS } from '../../../shared/world/forest';

/**
 * The Forest region (GDD §10.15/§10.17, Phase 8E.1). A BaseBiomeScene subclass that
 * drives the multi-screen Forest manifest (FOREST_SCREENS): walking into a screen
 * edge with a defined exit fade-transitions to the neighbouring screen, spawning the
 * player at the opposite edge.
 *
 * All 15 screens — including the hub `forest_anchorage` — use the deterministic
 * per-screen maps generated by gen-forest-screens.mjs (the legacy overworld.json
 * exception was removed in #107). The hub's generated map carries open perimeter gaps
 * at its four exits, so the manifest exits are walkable like every other screen.
 */
export class ForestScene extends BaseBiomeScene {
  constructor() {
    super({ key: 'ForestScene' });
  }

  init(data?: { screenId?: string; spawnEdge?: string }): void {
    this.screenId = data?.screenId ?? 'forest_anchorage';
    this.screenDef = FOREST_SCREENS.find((s) => s.id === this.screenId);
    window.__forestScreenId = this.screenId;
  }

  tilesetKey(): string {
    return 'forest';
  }

  mapKeyForScreen(id: string): string {
    return 'forest_' + id;
  }

  preload(): void {
    if (!this.textures.exists('forest')) {
      this.load.image('forest', 'assets/tiles/forest.png');
    }
    this.loadCommonAssets();
    // Every screen — including the hub — loads its deterministic generated map (#107).
    this.load.tilemapTiledJSON(
      this.mapKeyForScreen(this.screenId),
      `assets/maps/forest/${this.screenId}.json`,
    );
  }
}
